version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: pm2-runtime ecosystem.config.js

volumes:
  mongo-data: